version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "7000:7000"
    depends_on:
      - db-postgres

  db-postgres:
    container_name: db-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: Mats
      POSTGRES_PASSWORD: Mats2005
      POSTGRES_DB: AppDb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: