export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const PROJECTS_ROUTE = '/projects'
export const PROJECT_ROUTE = '/project/:id'
export const ADD_TASK_ROUTE = '/project/:id/add-task'
export const ADD_USER_ROUTE = '/project/:id/add-user'
export const USER_PROFILE = '/user'