export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const PROJECTS_ROUTE = '/projects'
export const PROJECT_ROUTE = '/project/:id'